name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: gabrielcs04
          svg_out_path: dist/github-contribution-grid-snake.svg
          palette: github            # A preset of color, one of [github, github-dark, github-light]
          color_snake: black         # Color of the snake

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
